import = [
"~/.config/alacritty/themes/coolnight.toml",
"~/.config/alacritty/keybindings.toml",
]

[ env ]
TERM = "xterm-256color"

[window]
    opacity = 0.8
    decorations = "Buttonless"
    dynamic_padding = false
    blur = true
    option_as_alt = "Both"

[window.padding]
    x = 12
    y = 12

[font]
    size = 18
    offset.x = 0 # for letter spacing (default = 0)
    offset.y = 1 # for line spacing 

[font.normal]
    family = "SFMono Nerd Font"
    style = "Regular"

[cursor.style]
  shape = "Underline"
